version: "3"
# all the containers have to declare inside services
services:
  # App service
  todoApp:
    build: .
    # image name
    image: todo
    # container name
    container_name: nest-todo
    # always restart the container if it stops.
    restart: always
    # docker run -t is allow
    tty: true
    # application port, this is take value from env file
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - todo-app-network

    # working directory
    working_dir: /var/www/todo-app
    # save (persist) data and also to share data between contain
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: 'mongo'
    container_name: db_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - todo-app-network
networks:
  todo-app-network:
    driver: bridge
volumes:
  mongodata:
